name: build

on: [push, pull_request]

jobs:
  check:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.13.0

      - name: Install LLVM 12
        run: |
          sudo apt-get update
          echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main" | sudo tee /etc/apt/sources.list.d/llvm12.list
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y llvm-12-dev libclang-12-dev clang-12

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config

      - name: Build Claml
        run: |
          ./build.sh || eval $(opam env) && make -j

      - name: Run test (regression)
        run: eval $(opam env) && make test
