name: build

on: [push, pull_request]

jobs:
  check:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.13.0

      - name: Install LLVM 12
        run: |
          sudo apt-get update
          echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main" | sudo tee /etc/apt/sources.list.d/llvm12.list
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y llvm-12-dev libclang-12-dev clang-12
      
      - name: Set LLVM 12 Paths
        run: |
          echo "LLVM_CONFIG=/usr/bin/llvm-config-12" >> $GITHUB_ENV
          echo "CC=clang-12" >> $GITHUB_ENV
          echo "CXX=clang++-12" >> $GITHUB_ENV
          echo "C_INCLUDE_PATH=/usr/lib/llvm-12/include:$C_INCLUDE_PATH" >> $GITHUB_ENV
          echo "CPLUS_INCLUDE_PATH=/usr/lib/llvm-12/include:$CPLUS_INCLUDE_PATH" >> $GITHUB_ENV
          echo "PATH=/usr/lib/llvm-12/bin:$PATH" >> $GITHUB_ENV

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config

      - name: Build Claml
        run: |
          ./build.sh || eval $(opam env) && make -j

      - name: Run test (regression)
        run: eval $(opam env) && make test
